# Generated by Django 5.1.3 on 2024-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_mail', models.CharField(max_length=50, verbose_name='Почта')),
                ('user_login', models.CharField(max_length=50, verbose_name='Логин')),
                ('user_password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('user_function', models.CharField(max_length=8, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
