# Generated by Django 5.1.3 on 2024-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_mail',
            field=models.CharField(max_length=50, unique=True, verbose_name='Почта'),
        ),
    ]
