# Generated by Django 5.1.3 on 2024-11-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.internship', verbose_name='Стажировка'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
