# Generated by Django 5.1.3 on 2024-12-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_internship_internshipmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='internship',
        ),
        migrations.AddField(
            model_name='users',
            name='internship',
            field=models.ManyToManyField(blank=True, to='main.internshipmodel', verbose_name='Стажировки'),
        ),
    ]
